### ISSUE TITLE
Error when manually enabling the charge animation.

### ISSUE THREAD

**Issue by BenchPressesBooks** [Gluwc/bar-card#1]
When working with HASS 0.88.1 and the latest version of this card (0.0.5) everything works great until you manually enable the charge animations with the following parameters:

```
  - type: 'custom:bar-card'
    entity: sensor.lr_window_south_battery
    title: Living Room South Window
    indicator: right
    animation: charge
    charge_entity: 'off'
    width: 40%
    severity:
      - value: 10
        hue: '0'
      - value: 25
        hue: '50'
      - value: 100
        hue: '120'
```

The following error can be observed:
`/customcards/custom-lovelace/bar-card/bar-card.js?track=false:370:65 Uncaught TypeError: Cannot read property 'state' of undefined
`

The fix for this issue is to change line 370 from
`          chargeEntityState = hass.states[config.charge_entity].state;
`
to
`          chargeEntityState = config.charge_entity;
`
